#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xa43a5804, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xd7d8c8cd, __VMLINUX_SYMBOL_STR(rpcauth_register) },
	{ 0x262e58a1, __VMLINUX_SYMBOL_STR(xdr_shift_buf) },
	{ 0x77aa25db, __VMLINUX_SYMBOL_STR(alloc_pages_current) },
	{ 0xeb3a9cfd, __VMLINUX_SYMBOL_STR(auth_domain_put) },
	{ 0x402b8281, __VMLINUX_SYMBOL_STR(__request_module) },
	{ 0x6f53ca99, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x31908c63, __VMLINUX_SYMBOL_STR(rpc_destroy_wait_queue) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x405c1144, __VMLINUX_SYMBOL_STR(get_seconds) },
	{ 0x841932c9, __VMLINUX_SYMBOL_STR(sunrpc_cache_update) },
	{ 0x4d26e13c, __VMLINUX_SYMBOL_STR(xdr_buf_read_netobj) },
	{ 0x1c9a2551, __VMLINUX_SYMBOL_STR(xdr_init_encode) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0x6c081661, __VMLINUX_SYMBOL_STR(cache_destroy_net) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0xb98d57c2, __VMLINUX_SYMBOL_STR(rpcauth_init_cred) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x9b8e999f, __VMLINUX_SYMBOL_STR(rpc_unlink) },
	{ 0x20000329, __VMLINUX_SYMBOL_STR(simple_strtoul) },
	{ 0x8f1efb7c, __VMLINUX_SYMBOL_STR(put_rpccred) },
	{ 0x703ed0aa, __VMLINUX_SYMBOL_STR(rpcauth_generic_bind_cred) },
	{ 0x2f14a14, __VMLINUX_SYMBOL_STR(rpc_init_wait_queue) },
	{ 0xf668ba9, __VMLINUX_SYMBOL_STR(svc_auth_unregister) },
	{ 0xafe95719, __VMLINUX_SYMBOL_STR(remove_proc_entry) },
	{ 0x448eac3e, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x9c4d0937, __VMLINUX_SYMBOL_STR(cache_register_net) },
	{ 0xffe5095d, __VMLINUX_SYMBOL_STR(groups_free) },
	{ 0x374e45c, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x3df90523, __VMLINUX_SYMBOL_STR(rpc_mkpipe_data) },
	{ 0xce016c81, __VMLINUX_SYMBOL_STR(rpc_mkpipe_dentry) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0xf52d5e30, __VMLINUX_SYMBOL_STR(nonseekable_open) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x843a4a04, __VMLINUX_SYMBOL_STR(xdr_reserve_space) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xec730387, __VMLINUX_SYMBOL_STR(_atomic_dec_and_lock) },
	{ 0xba974f2e, __VMLINUX_SYMBOL_STR(rpc_get_sb_net) },
	{ 0xf432dd3d, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x5d9b2494, __VMLINUX_SYMBOL_STR(xdr_buf_subsegment) },
	{ 0xb6836ad4, __VMLINUX_SYMBOL_STR(svcauth_unix_set_client) },
	{ 0x71de9b3f, __VMLINUX_SYMBOL_STR(_copy_to_user) },
	{ 0xe14dbf69, __VMLINUX_SYMBOL_STR(PDE_DATA) },
	{ 0xfaac72f5, __VMLINUX_SYMBOL_STR(cache_check) },
	{ 0x60ea2d6, __VMLINUX_SYMBOL_STR(kstrtoull) },
	{ 0xf3d8ff47, __VMLINUX_SYMBOL_STR(rpc_queue_upcall) },
	{ 0x8d2fa007, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x8b852a69, __VMLINUX_SYMBOL_STR(rpc_call_sync) },
	{ 0x755f4bd0, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0xc55df828, __VMLINUX_SYMBOL_STR(rpc_create) },
	{ 0x50fa11, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xedc8833a, __VMLINUX_SYMBOL_STR(sunrpc_cache_lookup) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x4652313b, __VMLINUX_SYMBOL_STR(rpc_call_null) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x3bdae399, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xea360854, __VMLINUX_SYMBOL_STR(xdr_init_decode) },
	{ 0xfba4d553, __VMLINUX_SYMBOL_STR(rpcauth_init_credcache) },
	{ 0xe97f4ce5, __VMLINUX_SYMBOL_STR(qword_get) },
	{ 0xc8e96dea, __VMLINUX_SYMBOL_STR(qword_addhex) },
	{ 0xe261dd82, __VMLINUX_SYMBOL_STR(rpcauth_lookup_credcache) },
	{ 0xaf6ae696, __VMLINUX_SYMBOL_STR(kstrndup) },
	{ 0x61651be, __VMLINUX_SYMBOL_STR(strcat) },
	{ 0xa11e7be9, __VMLINUX_SYMBOL_STR(kmalloc_dma_caches) },
	{ 0xa774f9d6, __VMLINUX_SYMBOL_STR(cache_unregister_net) },
	{ 0x841997e7, __VMLINUX_SYMBOL_STR(module_put) },
	{ 0xf22202c8, __VMLINUX_SYMBOL_STR(rpc_pipe_generic_upcall) },
	{ 0x2050817f, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0x80320dfa, __VMLINUX_SYMBOL_STR(rpc_destroy_pipe_data) },
	{ 0x73d9d773, __VMLINUX_SYMBOL_STR(svc_auth_register) },
	{ 0xf0fdf6cb, __VMLINUX_SYMBOL_STR(__stack_chk_fail) },
	{ 0x2eec63c9, __VMLINUX_SYMBOL_STR(xdr_encode_netobj) },
	{ 0xf45bc564, __VMLINUX_SYMBOL_STR(rpc_wake_up_status) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x308b733a, __VMLINUX_SYMBOL_STR(getboottime) },
	{ 0x1a281433, __VMLINUX_SYMBOL_STR(auth_domain_lookup) },
	{ 0x662ebc2a, __VMLINUX_SYMBOL_STR(rpc_release_client) },
	{ 0xaf3b2beb, __VMLINUX_SYMBOL_STR(cache_purge) },
	{ 0x2dd008ee, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x1fc8f9fd, __VMLINUX_SYMBOL_STR(rpc_put_sb_net) },
	{ 0xce7968e3, __VMLINUX_SYMBOL_STR(rpc_sleep_on) },
	{ 0xa315f0c2, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xd52bf1ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xe5919cb1, __VMLINUX_SYMBOL_STR(xdr_encode_opaque) },
	{ 0xc4ab9fa0, __VMLINUX_SYMBOL_STR(__module_get) },
	{ 0xcf21d241, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x2fe1f0aa, __VMLINUX_SYMBOL_STR(rpcauth_unregister) },
	{ 0x8ace8ca3, __VMLINUX_SYMBOL_STR(groups_alloc) },
	{ 0xd68ff876, __VMLINUX_SYMBOL_STR(proc_create_data) },
	{ 0xe1ac2bb8, __VMLINUX_SYMBOL_STR(sunrpc_net_id) },
	{ 0xfc201b66, __VMLINUX_SYMBOL_STR(sprint_oid) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xa75312bc, __VMLINUX_SYMBOL_STR(call_rcu_sched) },
	{ 0x5c8b5ce8, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x7a36ddbd, __VMLINUX_SYMBOL_STR(rpc_wake_up) },
	{ 0xfa66f77c, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0xd3f128ad, __VMLINUX_SYMBOL_STR(read_bytes_from_xdr_buf) },
	{ 0xfe2e820f, __VMLINUX_SYMBOL_STR(rpc_net_ns) },
	{ 0xb742fd7, __VMLINUX_SYMBOL_STR(simple_strtol) },
	{ 0x801572c2, __VMLINUX_SYMBOL_STR(rpcauth_destroy_credcache) },
	{ 0x46572a87, __VMLINUX_SYMBOL_STR(cache_create_net) },
	{ 0xb88bd7d4, __VMLINUX_SYMBOL_STR(xdr_inline_decode) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xb0e602eb, __VMLINUX_SYMBOL_STR(memmove) },
	{ 0x2a294f02, __VMLINUX_SYMBOL_STR(auth_domain_find) },
	{ 0x43b2bf58, __VMLINUX_SYMBOL_STR(rpc_shutdown_client) },
	{ 0x672d4f3e, __VMLINUX_SYMBOL_STR(xdr_write_pages) },
	{ 0x77e2f33, __VMLINUX_SYMBOL_STR(_copy_from_user) },
	{ 0x6d044c26, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0xf3d292c4, __VMLINUX_SYMBOL_STR(xdr_buf_from_iov) },
	{ 0xcce82123, __VMLINUX_SYMBOL_STR(xdr_buf_trim) },
	{ 0xcc739fca, __VMLINUX_SYMBOL_STR(try_module_get) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0x30100f20, __VMLINUX_SYMBOL_STR(rpc_put_task) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=sunrpc,oid_registry";

